spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hrmanage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: chen.yu
    password: suzhou@1