server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:/D:/Git Projects/SpringBootDemo/test;AUTO_SERVER=TRUE
    # url: jdbc:h2:mem:test   #不持久化，放在内存中
    # schema: classpath:db/schema-h2.sql #初始化建表
    # data: classpath:db/data-h2.sql #初始化数据
    username: "chenyu"
    password: "Suzhou@01"
    # Hikari 数据源专用配置
    hikari:

  h2:
    console:
      path: /h2-console
      enabled: true #必须配置，不然无法访问

  # JPA 相关配置
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

